### ISSUE TITLE
Include Testnet?

### ISSUE THREAD

**Issue by TheBigCohooNah** [6102bitcoin/bitcoin-intro#12]
New to github. Please let me know if I am initiating this conversation in the wrong location.

Do we think there is any benefit in starting off these newbies with testnet? While Its not as impactful to own testnetcoins. It does make mainnet less intimidating once you can play around with testnet.

**Comment by 6102bitcoin** [comment]
Good idea - thanks.

Ps. Perfect use of GitHub

**Comment by 6102bitcoin** [comment]
I think the recommended tools are generally good enough that people should be fine going straight into mainnet.
