### ISSUE TITLE
Remove step number from ids (i.e., future proof links) 

### ISSUE THREAD

**Issue by sgornick** [6102bitcoin/bitcoin-intro#3]
What if you decide something you add would fit best at step 10.  That means if I had linked to the existing step 10 ( https://bitcoin-intro.com/#step-10-bitcoin-micropayments ) that link would no longer position the page at all (as that specific ID no longer would exist).  By simply removing the "step-N" prefix, the link will work, even if later you do need to insert a step somewhere.

**Comment by 6102bitcoin** [comment]
I was not expecting that people would link to a specific link.

This is a good point. Any idea how to do this in a way that makes it clear which Step each Title refers to?

**Comment by sgornick** [comment]
> Any idea how to do this in a way that makes it clear which Step each Title refers to?

Sure, just remove the step number from the ID.

Example: Instead of id="step-10-bitcoin-micropayments", which permits:

https://bitcoin-intro.com/#step-10-bitcoin-micropayments 

The ID could just omit the step number, and be "id="step-bitcoin-micropayments".
 
https://bitcoin-intro.com/#step-bitcoin-micropayments
