### ISSUE TITLE
Trustpilot?

### ISSUE THREAD

**Issue by dmp1ce** [6102bitcoin/bitcoin-intro#36]
What is the purpose of the Trustpilot step for CashApp? Checking with the link, the rating is very low. It is like a reason to NOT use CashApp.

Isn't this guide enough to vouch for CashApp and not use Trustpilot?

**Comment by 6102bitcoin** [comment]
Thanks - you are probably right, I added the step because I have not used cash app myself, and therefore didn't want to recommend it unreservedly. It seems very popular and most people seem to have no issues so I'll remove the trustpilot step

**Comment by dmp1ce** [comment]
I don't know. Maybe you are right originally. Maybe people shouldn't use CashApp, but then I don't think it should be in the guide either. 🤷

**Comment by 6102bitcoin** [comment]
Overhauled this section - Now showing many different options.
