### ISSUE TITLE
Link to Bitcoin Core download instead of Node Launcher

### ISSUE THREAD

**Issue by dergigi** [6102bitcoin/bitcoin-intro#39]
I don't believe installing core via the node launcher is still the way to go, or is it? It doesn't seem that the node launcher is maintained still.

It's probably better just to link to the [bitcoincore.org download page](https://bitcoincore.org/en/download/).

**Comment by 6102bitcoin** [comment]
Yes, this should be updated

**Comment by 6102bitcoin** [comment]
Done
