### ISSUE TITLE
Suggestion for Step 7. Why Running a Full Node

### ISSUE THREAD

**Issue by citizen010** [6102bitcoin/bitcoin-intro#4]
__1) Helps the Network__

Running your own full node is the only way to have full control and to ensure that all the rules of Bitcoin are being followed. Nodes do this by rejecting blocks and transactions that don’t follow the consensus rules and by rejecting connections from peers that send them (or too many of them). 

In this sense, nodes are more important than hash power as they are the ones that verify that the blockchain is following the rules. Even with the longest Proof-of-Work chain, nodes will still determine if said chain follows the rules and whether or not it is accepted or ignored.

__2) Keeps you safe__

Running any kind of Bitcoin wallet that does not require you to run a full node means that you have to place a certain degree of trust in the service provider, something that shouldn’t be necessary with Bitcoin.

A web-based wallet requires you to trust the central node through which your transactions are broadcasted and even lightweight clients like Electrum require that you trust their servers. Even an SPV client requires trust in a third party since you are only downloading the blockchain headers and not verifying if the blockchain you follow respects the rules of the network or if it’s the longest blockchain.

__3)  Allows you to choose__

In the possible event of a hard fork where both blockchains remain active with economic activity on each side like the one in Ethereum/Ethereum Classic, running a full node is the only way you can validate the rules of the new or old blockchain, according to your preference. If you don’t run a full node, your opinion will not be considered and you will simply follow the blockchain that is given to you.

Running a full node of the client you support is also an indirect way of voting, which shows miners what rule set the users overwhelmingly support.

__4) Gives you a higher degree of privacy__

Using a centralized, lightweight or even SPV wallet will never be as private as running a full node. Since you rely on third-party servers to broadcast your transactions for you, those servers will be aware of which addresses belong to you.

This is true both for online wallets and lightweight clients. SPV nodes that rely on bloom filters leak considerable information about the addresses of Bitcoin users.

__5) It’s not that hard__

To less than tech-savvy users, running a full node may seem like a challenge. However, running a Bitcoin core full node is nothing more than simply downloading the latest Bitcoin core client version and running it.

The Bitcoin blockchain is over 200GB in size, so it may take a while to synchronize your node initially. However, Core’s latest release v0.18.1 improves on validation speed and network propagation performance, leading to much shorter sync and initial block download times.

If in doubt, you can find instructions that detail the process for multiple operating systems on Bitcoin.org.

__6) It’s not that expensive__

Running a node will require you to keep your computer on at all times – or at least for the majority of the day. While you can always turn your node on and off at will with this option, it is not a very practical one. Many users decide not to host their nodes locally on a physical computer, but rather on a rented virtual server.

Some users have also resorted to hosting nodes on far less demanding machines than computers. Someone, for example, is running a Bitcoin full node on Raspberry pi3 by pruning the blockchain  (deleting unnecessary data about transactions that are fully spent).

The minimum requirements for running a Bitcoin node outlined by Bitcoin Core are as follows:

+   Desktop or laptop hardware running recent versions of Windows, Mac OS X, or Linux.
+   250 gigabytes of free disk space
+   2 gigabytes of memory (RAM)
+   A broadband Internet connection with upload speeds of at least 400 kilobits (50 kilobytes) per second
+   An unmetered connection, a connection with high upload limits, or a connection you regularly monitor to ensure it doesn’t exceed its upload limits. It’s common for full nodes on high-speed connections to use 200 gigabytes upload or more a month. Download usage is around 20 gigabytes a month, plus around an additional 100 gigabytes the first time you start your node.
+   6 hours a day that your full node can be left running. (You can do other things with your computer while running a full node.) More hours would be better, and best of all would be if you can run your node continuously.

> Given the benefits outlined above, running a Bitcoin full node will guarantee that you’re not only boosting the performance of the Bitcoin network but also having more say on its future.

**Comment by 6102bitcoin** [comment]
Good Suggestions! Is this online anywhere else? Would you be able to put it somewhere (If you are happy I can make a PDF and link to it or put it on medium).

**Comment by citizen010** [comment]
Thanks! :smile: 
I had this TXT file around for some time. Probably the same content is online somewhere but I can't provide a link. 
Feel free to make a PDF or put it on medium as you prefer.
:+1:
